align term naming convention
inrupt/solid-common-vocab-rdf pull request #153
Opened 2023-05-22 08:35 UTC by pmcb55

Renamed terms to all be consistent, and using left-justification based on 'kind' of thing (i.e., 'storage' or 'container') as opposed to 'base'-ness or 'relative'-ness.

2023-05-23 16:28 UTC, jeswr requested changes

2023-05-23 16:28 UTC, jeswr commented on solid-rdf/CopyOfVocab/solid-data-discovery.ttl
> +    rdfs:label "Storage path (relative to...something)"@en ;
```suggestion
    rdfs:label "Storage path relative to the containerPathBase"@en ;
```

2023-05-23 16:28 UTC, jeswr commented on solid-rdf/CopyOfVocab/solid-data-discovery.ttl
> +    rdfs:label "Authored by"@en ;
```suggestion
    rdfs:label "An application that was used to author the resource"@en ;
```

2023-05-23 16:28 UTC, jeswr commented on solid-rdf/CopyOfVocab/solid-data-discovery.ttl
> +    rdfs:label "Allowed data model"@en ;
```suggestion
    rdfs:label "The shape, or non-RDF data model expected by the storageDescription"@en ;
```

2023-05-23 16:28 UTC, jeswr commented on solid-rdf/CopyOfVocab/solid-data-discovery.ttl
> +    rdfs:label "Container path (base)"@en ;
```suggestion
    rdfs:label "The (user provided) base container path that app should use when resolving a relative storage path"@en ;
```

2023-05-23 16:28 UTC, jeswr commented on solid-rdf/CopyOfVocab/solid-data-discovery.ttl
> +solid_dd:storagePathRelative a rdf:Property, owl:ObjectProperty ;
To me `relativeStoragePath` reads a lot more easily than `storagePathRelative`; as does `baseContainerPath` compared to `containerPathBase`.

2023-05-25 19:23 UTC, pmcb55 commented on solid-rdf/CopyOfVocab/solid-data-discovery.ttl
> +    rdfs:label "Authored by"@en ;
That seems too long for a 'label'. In my head (maybe a Best Practice to be added(?) (just as a simple '_rule of thumb_'), `rdfs:label` values can be considered the strings you'd display to the left of a text entry field on a UI - i.e., super short.
In that vein, I'd then consider the `rdfs:comment` values to be the text of a tooltip that pops up when the user hovers their mouse over that label or text field of that same UI - i.e., a longer description of what this property is.
So I'd consider your suggestion here to be a good `rdfs:comment` value, but not an `rdfs:label` value.

2023-05-25 19:23 UTC, pmcb55 commented on solid-rdf/CopyOfVocab/solid-data-discovery.ttl
> +    rdfs:label "Allowed data model"@en ;
Again, I'd consider this suggestion as an `rdfs:comment` value instead.

2023-05-25 19:27 UTC, pmcb55 commented on solid-rdf/CopyOfVocab/solid-data-discovery.ttl
> +    rdfs:label "Container path (base)"@en ;
Ditto - more an `rdfs:comment`.

2023-05-25 19:35 UTC, pmcb55 commented on solid-rdf/CopyOfVocab/solid-data-discovery.ttl
> +solid_dd:storagePathRelative a rdf:Property, owl:ObjectProperty ;
> ...reads a lot more easily than...

Yeah, I know, but that's my whole argument for switching to the 'left-justified' naming convention (we did this from day one in the Inrupt SDKs, and I think that demonstrates that it works well. We also did it at the start with ESS.
If you just name things 'naturally', then you end up with the inconsistencies we had originally in this vocab (and you also tend to have lot of plurals in names, which again leads to all kinds of weird naming inconsistencies (e.g., is it 'People' or 'Persons', etc.)).
So yes, it is a mental switch, but once made, it makes everything thereafter simple and consistent.
The idea here is to think of a 'Storage Path' as the primary thing here, and that primary thing can have a 'Base Value' and a 'Relative Value' - by left-justifying the 'primary thing' in the name, terms names collate nicely (i.e., appear together when alphabetically sorted) and it's much easier to conceptualize all the 'things associated with the primary thing' (e.g., in this case just 'base' and 'relative', but as you add more and more, this initial left-justification really becomes helpful).

2023-05-25 19:39 UTC, pmcb55 commented on solid-rdf/CopyOfVocab/solid-data-discovery.ttl
> +solid_dd:containerPathBase a rdf:Property, owl:ObjectProperty ;
I think this is just an artifact of my moving terms around in the Turtle - as yes indeed, I do suggest renaming `baseStorageContainer` to be `storageContainerBase` (since the 'primary thing' is the 'Storage Container').

2023-06-28 21:41 UTC, pmcb55 commented on solid-rdf/CopyOfVocab/solid-data-discovery.ttl
> +solid_dd:containerPathBase a rdf:Property, owl:ObjectProperty ;
Yeah, sorry for the mix up - I've lined-up the 'base' and 'relative' storage term names (and comments) now: f0c7fb0

2023-06-29 00:28 UTC, jeswr approved these changes

2023-06-29 08:22 UTC, merged